<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7V1kKSC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7V1kKSC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7V1kKSC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7V1kKSC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7V1kKSC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7V1kKSC',
    'container.build_id' => '65d89a58',
    'container.build_time' => 1611859708,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7V1kKSC');
